// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Syncthing adapter-settings": {
        "en": "Syncthing adapter-settings",
        "de": "Syncthing Adapter-Einstellungen",
        "ru": "Синхронизация настроек адаптера",
        "pt": "Adaptador de sincronização-configurações",
        "nl": "Syncthing-adapter-instellingen",
        "fr": "Syncthing adapter-settings",
        "it": "Impostazioni della scheda di sincronizzazione",
        "es": "Sincronización de ajustes del adaptador",
        "pl": "Synchronizowanie ustawień adaptera"
    },
    "Syncthing URL:": {
        "en": "Syncthing URL:",
        "de": "Syncthing-URL:",
        "ru": "Синхронизация URL:",
        "pt": "URL de sincronização:",
        "nl": "Syncthing-URL:",
        "fr": "Synchroniser l'URL:",
        "it": "URL di sincronizzazione:",
        "es": "URL de sincronización:",
        "pl": "Adres URL synchronizacji:"
    },
    "(e.g. http://127.0.0.1:8080)": {
        "en": "(e.g. http://127.0.0.1:8080)",
        "de": "(z.B. http://127.0.0.1:8080)",
        "ru": "(например, http://127.0.0.1:8080)",
        "pt": "(por exemplo, http://127.0.0.1:8080)",
        "nl": "(bijvoorbeeld http://127.0.0.1:8080)",
        "fr": "(par exemple http://127.0.0.1:8080)",
        "it": "(ad esempio http://127.0.0.1:8080)",
        "es": "(por ejemplo, http://127.0.0.1:8080)",
        "pl": "(np. http://127.0.0.1:8080)"
    },
    "Syncthing API-Key:": {
        "en": "Syncthing API-Key:",
        "de": "Syncthing-API-Schlüssel:",
        "ru": "Синхронизация API-ключа:",
        "pt": "Chave de API de sincronização:",
        "nl": "Syncthing API-Key:",
        "fr": "Syncthing API-Key:",
        "it": "Chiave API Syncthing:",
        "es": "Sincronización de API-Key:",
        "pl": "Synchronizacja klucza API:"
    },
    "(see Syncthing menu Actions/Advanced)": {
        "en": "(see Syncthing menu Actions/Advanced)",
        "de": "(siehe Syncthing Aktionen / Erweitert)",
        "ru": "(см. меню «Синхронизация» «Действия» / «Дополнительно»)",
        "pt": "(veja o menu Syncthing Actions / Advanced)",
        "nl": "(zie Syncthing menu Acties / Geavanceerd)",
        "fr": "(voir le menu Syncthing Actions / Avancé)",
        "it": "(vedi il menu Syncthing Azioni / Avanzate)",
        "es": "(ver Menú de Sincronización Acciones / Avanzado)",
        "pl": "(patrz Menu synchronizacji Akcje / Zaawansowane)"
    },
    "Syncthing Folder-ID:": {
        "en": "Syncthing Folder-ID:",
        "de": "Syncthing Folder-ID:",
        "ru": "Синхронизация идентификатора папки:",
        "pt": "Syncthing Folder-ID:",
        "nl": "Syncthing Folder-ID:",
        "fr": "Syncthing Folder-ID:",
        "it": "Syncthing Folder-ID:",
        "es": "Sincronización de ID de carpeta:",
        "pl": "Synchronizacja ID folderu:"
    },
    "(the ID of the Syncthing folder to be included)": {
        "en": "(the ID of the Syncthing folder to be included)",
        "de": "(Die ID des Syncthing-Ordners, der eingefügt werden soll)",
        "ru": "(идентификатор папки Syncthing, которая будет включена)",
        "pt": "(o ID da pasta Syncthing a ser incluída)",
        "nl": "(de ID van de Syncthing-map die moet worden opgenomen)",
        "fr": "(l'ID du dossier Syncthing à inclure)",
        "it": "(l'ID della cartella Syncthing da includere)",
        "es": "(la ID de la carpeta Syncthing que se incluirá)",
        "pl": "(identyfikator dołączanego folderu Syncthing)"
    }
}